### ISSUE TITLE
Rust 自己操作中的一些小问题

### ISSUE THREAD

**Issue by youlaiwuqu** [Conflux-DAO-TOC/sig-conflux-rust#2]
1.为什么我这样写，系统会报错？
```
fn other_function(a:i32,b:u32) {println!("a={},b={}",a,b)}
fn main(){let a:i32=-3;
let b:u32=4;
other_function(a:i32,b:u32);
}
```
2.如果没有主函数，直接运行定义的这个函数，为什么系统也会报错？
```
fn other_function(a:i32,b:u32) {println!("a={},b={}",a,b)}
```
3.为什么下面这种也会报错？是因为rust执行语句一从上到下的吗？
```
fn other_function(a:i32,b:u32) {println!("a={},b={}",a,b)}
fn main(){
other_function(a,b);
let a:i32=-3;
let b:u32=4;}
```
4.我发现3个语句写在同一行能运行成功。几个语句能写在同一行吗？但是要注意先后顺序？
```
fn other_function(a:i32,b:u32) {println!("a={},b={}",a,b)}
fn main(){

let a:i32=-3;let b:u32=4;other_function(a,b);
}
```

**Comment by xiaods** [comment]
1.为什么我这样写，系统会报错？
答案：
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3a73be205139bb923c6910cca545fc71

**Comment by xiaods** [comment]
新手定义：
你的代码格式没有格式化，代码没法看。这个习惯不好，缩进，格式化好看。

**Comment by youlaiwuqu** [comment]
以下为我改为格式化的。
1.为什么我这样写，系统会报错？
fn other_function(a: i32, b: u32) {
    println!("a={},b={}", a, b)
}
fn main() {
    let a: i32 = -3;
    let b: u32 = 4;
    other_function(a: i32, b: u32);
}
2.如果没有主函数，直接运行定义的这个函数，为什么系统也会报错？
fn other_function(a: i32, b: u32) {
    println!("a={},b={}", a, b)
}
3.为什么下面这种也会报错？是因为rust执行语句一从上到下的吗？
fn other_function(a: i32, b: u32) {
    println!("a={},b={}", a, b)
}
fn main() {
    other_function(a, b);
    let a: i32 = -3;
    let b: u32 = 4;
}
4.我发现3个语句写在同一行能运行成功。几个语句能写在同一行吗？但是要注意先后顺序？
fn other_function(a: i32, b: u32) {
    println!("a={},b={}", a, b)
}
fn main() {
    let a: i32 = -3;
    let b: u32 = 4;
    other_function(a, b);
}

**Comment by xiaods** [comment]
@youlaiwuqu  第一题我已经给你解答完了。你看看。

**Comment by youlaiwuqu** [comment]
> 1.为什么我这样写，系统会报错？
> 答案：
> https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3a73be205139bb923c6910cca545fc71

为什么调用的函数，other_function(a, b) 不能写成other_function(a:i32, b:u32)这种注明参数类型的格式？

**Comment by xiaods** [comment]
> > 1.为什么我这样写，系统会报错？
> > 答案：
> > https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3a73be205139bb923c6910cca545fc71
> 
> 为什么调用的函数，other_function(a, b) 不能写成other_function(a:i32, b:u32)这种注明参数类型的格式？

答：Rust语言设计成这个样子。是强制的。是一种约定。

**Comment by xiaods** [comment]
> 2.如果没有主函数，直接运行定义的这个函数，为什么系统也会报错？
> 
> fn other_function(a:i32,b:u32) {println!("a={},b={}",a,b)}
答：Rust语言规定，运行程序的入口必须是main函数。

**Comment by xiaods** [comment]
> 3.为什么下面这种也会报错？是因为rust执行语句一从上到下的吗？
> 
> fn other_function(a:i32,b:u32) {println!("a={},b={}",a,b)}
> fn main(){
> other_function(a,b);
> let a:i32=-3;
> let b:u32=4;}

答：程序执行的顺序都是从上到下执行的。所以代码中，当other_function调用时，入参a,b没有初始化。报错信息会给予你提示的。

**Comment by xiaods** [comment]
> 4.我发现3个语句写在同一行能运行成功。几个语句能写在同一行吗？但是要注意先后顺序？
> 
> fn other_function(a:i32,b:u32) {println!("a={},b={}",a,b)}
> fn main(){
> 
> let a:i32=-3;let b:u32=4;other_function(a,b);
> }

代码是给人看的，你写成一行，可读性就没有了。Rust对于格式提供了rustfmt工具。注意使用。
